# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperformanceprediction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dockertestvinay/
        username: ${{ secrets.AzureAppService_ContainerUsername_85e1368494aa493d921c3f86512ded24 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_23d870b9751546bcbf54b28c86d03cd4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dockertestvinay/${{ secrets.AzureAppService_ContainerUsername_85e1368494aa493d921c3f86512ded24 }}/studentperformanceprediction:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperformanceprediction'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_935da1f422754f2cbf8dabdf9c0e1b90 }}
        images: 'dockertestvinay/${{ secrets.AzureAppService_ContainerUsername_85e1368494aa493d921c3f86512ded24 }}/studentperformanceprediction:${{ github.sha }}'